IPB-1380: Added debug job to verify creation of docker image (#2163)

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -346,11 +346,38 @@ jobs:
     with:
       docker_registry: 'ghcr.io'
       registry_org: 'ministryofjustice'
-      additional_docker_tag: ""
       push: false
       upload_image_artifact: true
       docker_multiplatform: false
-      additional_docker_build_args: ""
+  verify_and_upload_image:
+    name: Verify Docker image artifact
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Download Docker image artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: build_image
+          path: ${{ runner.temp }}
+      - name: List artifact contents
+        run: ls -lh ${{ runner.temp }}
+      - name: Check for Docker image tarball
+        run: |
+          if [ ! -f ${{ runner.temp }}/build_image.tar ]; then
+            echo "Error: build_image.tar does not exist!"
+            exit 1
+          else
+            echo "build_image.tar found!"
+          fi
+      - name: Load Docker image
+        run: docker load -i ${{ runner.temp }}/build_image.tar
+
+      - name: Push Docker image to GHCR
+        run: |
+          IMAGE_NAME="ghcr.io/ministryofjustice/${{ github.repository }}"
+          docker tag "${IMAGE_NAME}:latest" "${IMAGE_NAME}:${{ needs.set_version.outputs.app_version }}"
+          docker push "${IMAGE_NAME}:${{ needs.set_version.outputs.app_version }}"
+          docker push "${IMAGE_NAME}:latest"
   set_version:
     name: Set app version
     needs: build
